### ISSUE TITLE
Create a JenkinsFile

### ISSUE THREAD

**Issue by Lutfar1996** [Lutfar1996/swiggy-app-deployment#2]
Anyone Out there who have an experience in Jenkins and created a automation for CI/CD ! ! ! Let me know

**Comment by CurlyBracess** [comment]
Yes Sir, I have an Experience in creating Jenkins CI/CD ! ! !

**Comment by Lutfar1996** [comment]
Ok, That's Cool. Create a new branch named "JENKINS" write a Jenkins File and then push it and create a new PR...

**Comment by CurlyBracess** [comment]
Ok

**Comment by Lutfar1996** [comment]
The issue is solved, thanks Curly braces
